CREATE DATABASE bookstore;

USE bookstore;

CREATE TABLE BOOK(
	BOOK_ID INTEGER NOT NULL,
	TITLE VARCHAR(20),
	ISBN VARCHAR(10),
	PRICE INTEGER,	
	AUTHOR_ID INTEGER,
	PUBLICATION_DATE DATE,
	StockQuantity INTEGER
	/*CONSTRAINTS pk_bid PRIMARY KEY(BOOK_ID),*/
/*	CONSTRAINTS a_id FOREIGN KEY(AUTHOR_ID) REFERENCES  ORDER
	(AUTHOR_ID)*/
 )

CREATE TABLE AUTHOR(
	AUTHOR_ID INTEGER,
	FIRST_NAME VARCHAR() NOT NULL,
	LAST_NAME VARCHAR() NOT NULL,
	--CONSTRAINTS pk_aid PRIMARY KEY(AUTHOR_ID)
)

CREATE TABLE CUSTOMER
(
CUSTOMER_ID INTEGER,
FIRST_NAME VARCHAR(20) NOT NULL,
LAST_NAME VARCHAR(20) NOT NULL ,
EMAIL VARCHAR(20) NOT NULL,
PHONE VARCHAR (11) NOT NULL,
--CONSTRAINTS pk_cid PRIMARY KEY(CUSTOMER_ID)
)

CREATE TABLE ORDER(
	ORDER_ID INTEGER,
	ORDER_DATE DATE,
	CUSTOMER_ID INTEGER,
	TOTAL_AMOUNT INTEGER,
	--CONSTRAINTS pk_oid PRIMARY KEY(ORDER_ID),
--	CONSTRAINTS fk_cid FOREIGN KEY(CUSTOMER_ID) REFERENCES  ORDER
--	(CUSTOMER_ID)
)

CREATE TABLE SALES(
SALES_ID INTEGER,
SALES_DATE DATE,
ORDER_ID INTEGER,
BOOK_ID INTEGER,
Quantity INTEGER,
FINAL_PRICE INTEGER,

--CONSTRAINTS pk_sid PRIMARY KEY(SALES_ID),
--CONSTRAINTS fk_oid FOREIGN KEY(ORDER_ID) REFERENCES  ORDER(ORDER_ID),
--CONSTRAINTS fk_bid FOREIGN KEY(BOOK_ID) REFERENCES  ORDER(BOOK_ID)
)


